--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/02/2022 3:42:21 p. m.
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

CREATE DATABASE progracol;

--
-- Set default database
--
USE progracol;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Drop table `product_category`
--
DROP TABLE IF EXISTS product_category;

--
-- Drop table `category`
--
DROP TABLE IF EXISTS category;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Set default database
--
USE progracol;

--
-- Create table `product`
--
CREATE TABLE product (
  id int NOT NULL AUTO_INCREMENT,
  creation_date datetime NOT NULL DEFAULT (NOW()),
  description varchar(100) DEFAULT NULL,
  expiry_date datetime DEFAULT NULL,
  name varchar(45) DEFAULT NULL,
  price int DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 16,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `category`
--
CREATE TABLE category (
  id int NOT NULL AUTO_INCREMENT,
  description varchar(100) DEFAULT NULL,
  name varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `product_category`
--
CREATE TABLE product_category (
  id int NOT NULL AUTO_INCREMENT,
  id_product int DEFAULT NULL,
  id_category int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `id_product_category_idx` on table `product_category`
--
ALTER TABLE product_category
ADD INDEX id_product_category_idx (id_product);

--
-- Create index `id_category_product_idx` on table `product_category`
--
ALTER TABLE product_category
ADD INDEX id_category_product_idx (id_category);

--
-- Create foreign key
--
ALTER TABLE product_category
ADD CONSTRAINT id_category_product FOREIGN KEY (id_category)
REFERENCES category (id);

--
-- Create foreign key
--
ALTER TABLE product_category
ADD CONSTRAINT id_product_category FOREIGN KEY (id_product)
REFERENCES product (id);

--
-- Create table `customer`
--
CREATE TABLE customer (
  id int NOT NULL AUTO_INCREMENT,
  email varchar(50) DEFAULT NULL,
  identificacion varchar(45) DEFAULT NULL,
  name varchar(45) DEFAULT NULL,
  phone varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table product
--
INSERT INTO product VALUES
(1, '2022-02-03 15:41:53', 'Producto001', NULL, 'Producto001', 5),
(2, '2022-02-03 21:33:21', 'Producto002', NULL, 'Producto002', 6),
(3, '2022-02-03 21:33:30', 'Producto003', NULL, 'Producto003', 87),
(4, '2022-02-03 21:33:30', 'Producto004 - Ha cambiado...!! ', NULL, 'Producto004', 56),
(5, '2022-02-03 22:04:57', 'Producto005 - Ha cambiado...!! ', NULL, 'Producto005', 107),
(9, '2022-02-04 00:49:49', 'Producto009', NULL, 'Producto009', 236),
(10, '2022-02-04 00:49:49', 'Producto010', NULL, 'Producto010', 276),
(11, '2022-02-04 01:03:03', 'Producto011', NULL, 'Producto011', 276),
(14, '2022-02-04 02:15:45', 'Producto012', NULL, 'Producto012', 276);

-- 
-- Dumping data for table category
--
INSERT INTO category VALUES
(1, 'Category001', 'Category001');

-- 
-- Dumping data for table product_category
--
INSERT INTO product_category VALUES
(1, 14, 1);

-- 
-- Dumping data for table customer
--
-- Table progracol.customer does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;